### ISSUE TITLE
Get start error An exception of type 'StructureMap.StructureMapException'

### ISSUE THREAD

**Issue by nguyenquynhan** [jgeurts/MvcKickstart#6]
Can you help me this error?
public static void PreStart() 
		{
			var db = ObjectFactory.GetInstance<IDbConnection>(); //Error here
			if (!db.TableExists(db.GetTableName<DataMigration>()))
			{
				db.CreateTable<DataMigration>();
			}
			var alreadyExecutedMigrations = db.Query<DataMigration>("select * from [{0}]".Fmt(db.GetTableName<DataMigration>()));
			var migrationTypes = GetMigrationTypes();
			foreach (var migration in migrationTypes.Where(t => !alreadyExecutedMigrations.Any(m => m.Name == t.Name)).Select(x => (IMigration)Activator.CreateInstance(x)).OrderBy(x => x.Order))
			{
				migration.Execute(db);
				// add migration to database
				var migrationData = new DataMigration
					                    {
						                    CreatedOn = DateTime.UtcNow,
						                    Name = migration.GetType().Name
					                    };
				db.Save(migrationData);
			}
		}

An exception of type 'StructureMap.StructureMapException' occurred in StructureMap.dll but was not handled in user code

**Comment by nguyenquynhan** [comment]
I have configed connectionString in web.config but connect sql fail:
Cannot open database "KickstartTemplate" requested by the login. The login failed.
Login failed for user 'NHANSOFT\NHAN'.

**Comment by jgeurts** [comment]
Does the sql database exist referenced by your connection string?

**Comment by nguyenquynhan** [comment]
Good! I resolve error!
Thanks jgeurts vary much!
